org: feden
app: march-2023-sls
service: march-2023-sls
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  versionFunctions: true
  timeout: 15
  environment:
    MONGO_URL: ${param:MONGO_URL}

functions:
  createTodo:
    handler: src/handlers/createTodo.handler
    events:
      - httpApi:
          path: /todos
          method: post
  getTodos:
    handler: src/handlers/getTodos.handler
    events:
      - httpApi:
          path: /todos
          method: get

  getTodo:
    handler: src/handlers/getTodo.handler
    events:
      - httpApi:
          path: /todos/{todoId}
          method: get
  updateTodo:
    handler: src/handlers/updateTodo.handler
    events:
      - httpApi:
          path: /todos/{todoId}
          method: patch
  deleteTodo:
    handler: src/handlers/deleteTodo.handler
    events:
      - httpApi:
          path: /todos/{todoId}
          method: delete

  sch:
    handler: src/handlers/sdasd.handler
    events:
      - schedule: rate(1 minute)
